STM32MP1xx add SPI LL
arnop2/hal_stm32 pull request #1
Opened 2019-06-20 09:30 UTC by yboutreux

CMSIS register modification are cherry-picked from Cube CMSIS v1.1.0.rc1, modifications non-related to SPI hadn't been selected.
Add SPI LL for STM32MP1x SoC.

DO NOT MERGE because before going to upstream they need to be provided a ST Bug Tracker ID, this PR has only a review purpose

Signed-off-by: Yaël Boutreux <yael.boutreux@st.com>

2019-06-21 10:08 UTC, erwango requested changes
Last commit miss update on stm32cube/stm32mp1xx/CMakeLists.txt

2019-06-24 07:44 UTC, yboutreux commented
> Last commit miss update on stm32cube/stm32mp1xx/CMakeLists.txt

Updated to add changes on stm32cube/stm32mp1xx/README

2019-06-25 13:42 UTC, erwango requested changes

2019-06-25 13:42 UTC, erwango commented on stm32cube/stm32mp1xx/README
> +    ST Bug tracker ID: None
@yboutreux , can you give expected release version here?

2019-06-26 07:38 UTC, yboutreux commented on stm32cube/stm32mp1xx/README
> +    ST Bug tracker ID: None
> @yboutreux , can you give expected release version here?

Modification done

2019-06-26 07:39 UTC, yboutreux commented
I also added the Cube version inside the commit

2019-07-04 09:30 UTC, atorgue commented on stm32cube/stm32mp1xx/drivers/src/stm32mp1xx_ll_spi.c
> +/**
why those empty lines ?

2019-07-04 09:32 UTC, atorgue approved these changes

2019-07-04 12:02 UTC, yboutreux commented on stm32cube/stm32mp1xx/drivers/src/stm32mp1xx_ll_spi.c
> +/**
Picked directly code generated for CubeMP1

2019-07-25 08:04 UTC, yboutreux commented
PR closed since it went as an official PR on Zephyrproject

2019-07-25 08:04 UTC, closed without merging